codesyncapp/codesync-intellij

CHANGELOG.md, build.gradle, src/main/java/icons/CodeSyncIcons.java, src/main/java/icons/SdkIcons.java, src/main/java/org/intellij/sdk/codesync/CodeSyncLogger.java, src/main/java/org/intellij/sdk/codesync/Constants.java, src/main/java/org/intellij/sdk/codesync/NotificationManager.java, src/main/java/org/intellij/sdk/codesync/ProjectOpenCloseListener.java, src/main/java/org/intellij/sdk/codesync/actions/FilePlaybackAction.java, src/main/java/org/intellij/sdk/codesync/auth/AuthAction.java, src/main/java/org/intellij/sdk/codesync/codeSyncSetup/CodeSyncSetup.java, src/main/java/org/intellij/sdk/codesync/ui/messages/CodeSyncMessages.java, src/main/java/org/intellij/sdk/codesync/ui/progress/InitRepoMilestones.java, src/main/java/org/intellij/sdk/codesync/utils/CommonUtils.java, src/main/resources/META-INF/plugin.xml
__Description:__
- Added platform name in the CW log event.
- Updated handling for notifications and deprecated the old API to start using the new one.
- Added CodeSync icon on user input dialogs.
- We should not handle updates for projects that disposed.
- Updated wording of notifications to correctly indicate repo or branch that is being synced.
=> Plugin updates that include better logging, bug fixes and correct notification messages

CHANGELOG.md, build.gradle, src/main/java/org/intellij/sdk/codesync/Constants.java, src/main/java/org/intellij/sdk/codesync/HandleBuffer.java, src/main/java/org/intellij/sdk/codesync/auth/Authenticator.java, src/main/java/org/intellij/sdk/codesync/clients/ClientUtils.java, src/main/java/org/intellij/sdk/codesync/clients/CodeSyncClient.java, src/main/java/org/intellij/sdk/codesync/clients/CodeSyncWebSocketClient.java, src/main/java/org/intellij/sdk/codesync/clients/JSONResponse.java, src/main/java/org/intellij/sdk/codesync/codeSyncSetup/CodeSyncSetup.java, src/main/java/org/intellij/sdk/codesync/exceptions/response/StatusCodeError.java, src/main/java/org/intellij/sdk/codesync/files/LockFile.java, src/main/java/org/intellij/sdk/codesync/locks/CodeSyncLock.java, src/main/java/org/intellij/sdk/codesync/utils/CommonUtils.java, src/main/java/org/intellij/sdk/codesync/utils/PricingAlerts.java
This PR adds pricing alert for users who have used up available resources and need to upgrade account in order to continue using codesync.
=>  Pricing alert checks added.

CHANGELOG.md, build.gradle, src/main/java/org/intellij/sdk/codesync/HandleBuffer.java, src/main/java/org/intellij/sdk/codesync/PopulateBuffer.java, src/main/java/org/intellij/sdk/codesync/files/SequenceTokenFile.java, src/main/java/org/intellij/sdk/codesync/utils/FileUtils.java, src/main/java/org/intellij/sdk/codesync/utils/PricingAlerts.java
In this PR, I have updated the daemon logic that handles diff file upload to delete the dangling diff files belonging to a branch that no longer exists.
Previously, we were getting a lot of logs related to this.
=> feat: Added handling for dangling diff files belonging to a branch that does not exist anymore.

CHANGELOG.md, build.gradle, src/main/java/org/intellij/sdk/codesync/CodeSyncLogger.java, src/main/java/org/intellij/sdk/codesync/Constants.java, src/main/java/org/intellij/sdk/codesync/PopulateBuffer.java, src/main/java/org/intellij/sdk/codesync/clients/CodeSyncWebSocketClient.java, src/main/java/org/intellij/sdk/codesync/codeSyncSetup/CodeSyncSetup.java, src/main/java/org/intellij/sdk/codesync/files/ConfigFile.java, src/main/java/org/intellij/sdk/codesync/ui/dialogs/PricingAlertDialog.java, src/main/java/org/intellij/sdk/codesync/utils/DiffUtils.java
- Improved pricing alert dialog box.
- Improved error handling during repo init flow.
- Added IDE name in logging and GA4 tags for better understanding of errors.
- Added analytics tag for websocket connections.
- Fixed new file creation timestamp in diff files.
=> fix: Fixes and improvements in the plugin.

CHANGELOG.md, build.gradle, src/main/java/org/intellij/sdk/codesync/Constants.java, src/main/java/org/intellij/sdk/codesync/HandleBuffer.java, src/main/java/org/intellij/sdk/codesync/PopulateBuffer.java, src/main/java/org/intellij/sdk/codesync/alerts/ActivityAlerts.java, src/main/java/org/intellij/sdk/codesync/alerts/PricingAlerts.java, src/main/java/org/intellij/sdk/codesync/codeSyncSetup/CodeSyncSetup.java, src/main/java/org/intellij/sdk/codesync/codeSyncSetup/CodeSyncSetupAction.java, src/main/java/org/intellij/sdk/codesync/files/AlertsFile.java, src/main/java/org/intellij/sdk/codesync/files/LockFile.java, src/main/java/org/intellij/sdk/codesync/files/UserFile.java, src/main/java/org/intellij/sdk/codesync/ui/dialogs/PricingAlertDialog.java, src/main/java/org/intellij/sdk/codesync/utils/CommonUtils.java, src/main/java/org/intellij/sdk/codesync/utils/ProjectUtils.java
- Fixes and improvements in the plugin.
- Show login prompt before repo-sync prompt.
- Added handling and guards agains null values of Project instance in different places inside the code base. This will help avoid null pointer exceptions.
- Explicitly set API timeout to 120 seconds for requests, also refactored client related code to add better error handling and make it cleaner.
- Included `added_at` parameter for new files so that correct time is used if user creates a file during the time period when user's plan has expired.
- Added daily reminder alert for team activity review.
- Started using ScheduledExecutorService instead of Timer to schedule async processes.
- In case user has exhausted his plan limit we should show dialog in user tries to connect a new repo using actions.
- …
=> More fixes and enhancements.

CHANGELOG.md, build.gradle, src/main/java/org/intellij/sdk/codesync/Constants.java, src/main/java/org/intellij/sdk/codesync/HandleBuffer.java, src/main/java/org/intellij/sdk/codesync/PopulateBuffer.java, src/main/java/org/intellij/sdk/codesync/ProjectOpenCloseListener.java, src/main/java/org/intellij/sdk/codesync/alerts/ActivityAlerts.java, src/main/java/org/intellij/sdk/codesync/alerts/PricingAlerts.java, src/main/java/org/intellij/sdk/codesync/codeSyncSetup/CodeSyncSetup.java, src/main/java/org/intellij/sdk/codesync/files/AlertsFile.java, src/main/java/org/intellij/sdk/codesync/files/CodeSyncYmlFile.java, src/main/java/org/intellij/sdk/codesync/files/LockFile.java, src/main/java/org/intellij/sdk/codesync/locks/CodeSyncLock.java, src/main/java/org/intellij/sdk/codesync/utils/ProjectUtils.java
Bug fixes for daemon processes, yml files, locking logic, alerts and progress indicator.
- Bug fixes related to daemon processes and yml files.
- Refactored and improved locking logic to handle edge cases.
- Fixed a bug with progress indicator, it should work correctly now.
- Fixed a bug with activity alerts that was blocking alerts if user clicked on remind later.
=> fix: Bug fixes for daemon processes, yml files, locking logic, alerts and progress indicator.

src/main/java/org/intellij/sdk/codesync/Constants.java, src/main/java/org/intellij/sdk/codesync/codeSyncSetup/CodeSyncSetup.java, src/main/java/org/intellij/sdk/codesync/ui/dialogs/RepoPublicPrivateDialog.java
Converted message box to Dialog Box for Public-Private repository option.
=> Converted message box to DialogBox for Public-Private repository option.

build.gradle, src/main/java/org/intellij/sdk/codesync/Constants.java, src/main/java/org/intellij/sdk/codesync/auth/CodeSyncAuthServer.java, src/main/java/org/intellij/sdk/codesync/auth/LogoutAction.java, src/main/java/org/intellij/sdk/codesync/clients/CodeSyncClient.java
I have added source and plugin version on endpoints.
=> Adding IDE source and Plugin version on endpoints.

CHANGELOG.md, build.gradle, src/main/java/org/intellij/sdk/codesync/alerts/ActivityAlerts.java, src/main/java/org/intellij/sdk/codesync/files/LockFile.java
__Testing Instructions:__
1. Activity alerts should appear after 4:30 PM
=> fix: Fixed a bug that was causing suppression on dialogs.

CHANGELOG.md, build.gradle, src/main/java/org/intellij/sdk/codesync/CodeSyncLogger.java, src/main/java/org/intellij/sdk/codesync/HandleBuffer.java, src/main/java/org/intellij/sdk/codesync/PopulateBuffer.java, src/main/java/org/intellij/sdk/codesync/ProjectOpenCloseListener.java, src/main/java/org/intellij/sdk/codesync/Utils.java, src/main/java/org/intellij/sdk/codesync/alerts/ActivityAlerts.java, src/main/java/org/intellij/sdk/codesync/auth/LogoutAction.java, src/main/java/org/intellij/sdk/codesync/clients/CodeSyncClient.java, src/main/java/org/intellij/sdk/codesync/clients/WebSocketClientEndpoint.java, src/main/java/org/intellij/sdk/codesync/files/CodeSyncYmlFile.java, src/main/java/org/intellij/sdk/codesync/ui/dialogs/RepoPublicPrivateDialog.java
This PR adds logging in the activity alerts feature, this will help us in debugging the cause of the problem with activity alerts feature in production plugin version.
=> chore (logging): Added logging to debug activity alerts feature in production environment.

src/main/java/org/intellij/sdk/codesync/Constants.java, src/main/java/org/intellij/sdk/codesync/HandleBuffer.java, src/main/java/org/intellij/sdk/codesync/PopulateBuffer.java, src/main/java/org/intellij/sdk/codesync/alerts/ActivityAlerts.java
**Testing:**
1. User should get activity alert notification after 4:30 PM.
=> fix: Moved the logic that show activity alert dialog to EDT.

CHANGELOG.md, build.gradle, src/main/java/org/intellij/sdk/codesync/alerts/PricingAlerts.java, src/main/java/org/intellij/sdk/codesync/codeSyncSetup/CodeSyncSetup.java, src/main/java/org/intellij/sdk/codesync/ui/dialogs/RepoPublicPrivateDialog.java
__Testing Instructions:__
1. Users should see dialog boxes who were previously getting error for dialogs on the production version.
=> feat: Updated supported versions and also fixed a few dialog related issues.

CHANGELOG.md, build.gradle, src/main/java/org/intellij/sdk/codesync/CodeSyncLogger.java, src/main/java/org/intellij/sdk/codesync/configuration/DevConfiguration.java, src/main/java/org/intellij/sdk/codesync/files/ConfigFile.java, src/test/java/org/intellij/sdk/codesync/files/ConfigFileTest.kt, test_data/files/invalid-config.yml, test_data/files/valid-config.yml
_Description:__
This PR contains following changes
- Added tests for config file updates, updated logic so that async writes and locking wait do not cause the loss of data added in previous writes.
- Added more error handling for cloud watch logs so that it gracefully handles errors and does not interrupt users.
- Make sure thread waiting on lock release does not override the contents of previous write.
=> Fixed bugs, added test cases and handling for some edge case scenarios.

src/main/java/org/intellij/sdk/codesync/configuration/ProdConfiguration.java, src/main/java/org/intellij/sdk/codesync/configuration/TestConfiguration.java
Project opens without internet connection but diffs are not being processed when internet connections resumes. IDE have to restart to process the the diffs.
=> Resolving synced project not opening when internet is down.

CHANGELOG.md, README.md
Updated dark themed playback picture in README file.
=> Updated playback picture on repository.

CHANGELOG.md, build.gradle
Updating CHANGELOG and gradle file for version change.
=> Updated CHANGELOG and gradle file for version

build.gradle
=> Update version on gradle.

CHANGELOG.md, build.gradle
Removed unitBuild value causing issue in latest version on Intellij IDE.
=> Remvoed unitBuild value

CHANGELOG.md, build.gradle, src/main/java/org/intellij/sdk/codesync/Constants.java, src/main/java/org/intellij/sdk/codesync/HandleBuffer.java, src/main/java/org/intellij/sdk/codesync/Utils.java, src/main/java/org/intellij/sdk/codesync/clients/CodeSyncClient.java, src/main/java/org/intellij/sdk/codesync/exceptions/InvalidUsage.java, src/main/resources/META-INF/plugin.xml, src/test/java/org/intellij/sdk/codesync/clients/CodeSyncClientTest.kt
- Handling 400 response gracefully which is being received due to file being in syncignore.
- Updated dark themed playback image which will show up on Intellij Marketplace Plugin page.
- Removed log related to file being in repo ignore.
**Testing Instructions**
- Sync a project and in that project create a new file with extension of .jar. The file will not be synchronized and you will see log `file is in syncignore` for that file.
=> August 2023 Fixes

CHANGELOG.md, build.gradle, src/main/java/org/intellij/sdk/codesync/ProjectOpenCloseListener.java, src/main/java/org/intellij/sdk/codesync/Utils.java, src/main/java/org/intellij/sdk/codesync/codeSyncSetup/CodeSyncSetup.java, src/main/java/org/intellij/sdk/codesync/codeSyncSetup/CodeSyncSetupAction.java, src/test/java/org/intellij/sdk/codesync/UtilsTest.kt
**Testing Instructions**
- Open a project or directory that is not synced, you will notice popup will appear to sync the project.
- Open any individual file and before you open an individual file make sure you close already open project from File menu using 'Close Project'. When you will open an individual file you will notice sync popup is not being shown.
=> Avoid connect repo when individual file is open.

CHANGELOG.md, build.gradle, src/main/java/org/intellij/sdk/codesync/Constants.java, src/main/java/org/intellij/sdk/codesync/alerts/ActivityAlertActions.java, src/main/java/org/intellij/sdk/codesync/alerts/ActivityAlertNotification.java, src/main/java/org/intellij/sdk/codesync/alerts/ActivityAlerts.java, src/main/resources/META-INF/plugin.xml
**Testing Instructions**
- Delete the `project_locks` file in `.locks` folder.
- In `Constants.java` file on line 47 change change the value of variable `DELAY_BETWEEN_ACTIVITY_ALERT_TASKS` to `2 * 60 * 1000`
- In `ActivityAlerts.java` file on line 107 replace the condition with false and on line 113 also replace it with true..
- Team Activity Notification should show up within 2 minutes and you can test all three buttons.
=> Raplced dialogbox to bubble notification for Activity Alert

CHANGELOG.md, build.gradle, src/main/java/org/intellij/sdk/codesync/Constants.java, src/main/java/org/intellij/sdk/codesync/PopulateBuffer.java, src/main/java/org/intellij/sdk/codesync/clients/CodeSyncClient.java, src/main/java/org/intellij/sdk/codesync/codeSyncSetup/CodeSyncSetup.java, src/main/java/org/intellij/sdk/codesync/codeSyncSetup/S3FileUploader.java, src/main/java/org/intellij/sdk/codesync/codeSyncSetup/S3FilesUploader.java, src/main/java/org/intellij/sdk/codesync/files/CodeSyncYmlFile.java, src/main/java/org/intellij/sdk/codesync/files/S3UploadQueueFile.java, src/main/java/org/intellij/sdk/codesync/ui/progress/InitRepoMilestones.java
This PR adds the capability for async file upload to S3, this will reduce repo sync time and give better capability to recover from network errors while uploading S3 files.
**Testing Instructions:**
1. Sync a new repo and make sure files are being uploaded to S3 and are appearing on codesync.com
=> Async file uploads to S3

CHANGELOG.md, build.gradle, src/main/java/org/intellij/sdk/codesync/HandleBuffer.java, src/main/java/org/intellij/sdk/codesync/PopulateBuffer.java, src/main/java/org/intellij/sdk/codesync/Utils.java, src/main/java/org/intellij/sdk/codesync/actions/FilePlaybackAction.java, src/main/java/org/intellij/sdk/codesync/clients/CodeSyncClient.java, src/main/java/org/intellij/sdk/codesync/clients/CodeSyncWebSocketClient.java, src/main/java/org/intellij/sdk/codesync/codeSyncSetup/CodeSyncSetup.java, src/main/java/org/intellij/sdk/codesync/files/ConfigRepo.java, src/main/java/org/intellij/sdk/codesync/files/DiffFile.java, src/main/java/org/intellij/sdk/codesync/utils/DiffUtils.java, src/main/java/org/intellij/sdk/codesync/utils/GitUtils.java
Added `commit_hash` to the payload of each history event.
=> feat: Added commit_hash to each diff file.

CHANGELOG.md, build.gradle, src/main/java/org/intellij/sdk/codesync/Constants.java, src/main/java/org/intellij/sdk/codesync/clients/CodeSyncWebSocketClient.java, src/main/java/org/intellij/sdk/codesync/clients/JSONResponse.java
- Plugin now only checks for an error_code when a 402 status_code is recieved
=> Added handling for error_code

CHANGELOG.md, src/main/java/org/intellij/sdk/codesync/Constants.java, src/main/java/org/intellij/sdk/codesync/auth/AuthAction.java, src/main/java/org/intellij/sdk/codesync/auth/Authenticator.java, src/main/java/org/intellij/sdk/codesync/auth/CodeSyncAuthServer.java, src/main/java/org/intellij/sdk/codesync/codeSyncSetup/CodeSyncSetup.java, src/main/java/org/intellij/sdk/codesync/commands/ResumeCodeSyncCommand.java
This PR implements unified browser login and logout for intelliJ IDEs.
Testing instructions:
- You should be able to perform login and logout without any issues.
=> Unified browser login and logout for intelliJ plugin.

src/main/java/org/intellij/sdk/codesync/HandleBuffer.java, src/main/java/org/intellij/sdk/codesync/PopulateBuffer.java, src/main/java/org/intellij/sdk/codesync/ProjectOpenCloseListener.java, src/main/java/org/intellij/sdk/codesync/auth/CodeSyncAuthServer.java, src/main/java/org/intellij/sdk/codesync/clients/CodeSyncClient.java, src/main/java/org/intellij/sdk/codesync/codeSyncSetup/CodeSyncSetup.java, src/main/java/org/intellij/sdk/codesync/codeSyncSetup/S3FileUploader.java, src/main/java/org/intellij/sdk/codesync/codeSyncSetup/S3FilesUploader.java, src/main/java/org/intellij/sdk/codesync/state/StateUtils.java
This PR fixes the following bugs
1. Missing access token issue was causing errors for some users, this code will now check access token on startup and prompt user login window if access token is missing.
2. Path generation for login action was causing error on windows, I am now using `URI`'s `resolve` method to construct the path and hence that error will go away.
3. Added handling for some possible edge cases for S3 file upload and enhanced logging to find bugs faster in the future.
4. Fixed a message formatting issue.
**Testing Instructions:**
1. Click `Login` from CodeSync menu and make sure you are redirected to login page.
2. Make sure new files and files while syncing the repo are being uploaded to S3.
3. Manually set `access_token` to null in the codesync plugin database and open a …
=> fix: Fixed bugs in authentication flow ans S3 file uploads.

src/main/java/org/intellij/sdk/codesync/CodeSyncStartupActivity.java, src/main/java/org/intellij/sdk/codesync/actions/BaseModuleAction.java, src/main/java/org/intellij/sdk/codesync/actions/FilePlaybackAction.java, src/main/java/org/intellij/sdk/codesync/actions/RepoPlaybackAction.java, src/main/java/org/intellij/sdk/codesync/codeSyncSetup/CodeSyncSetupAction.java, src/main/java/org/intellij/sdk/codesync/database/tables/RepoTable.java, src/main/java/org/intellij/sdk/codesync/state/RepoStatus.java, src/main/java/org/intellij/sdk/codesync/state/StateUtils.java, src/main/resources/META-INF/plugin.xml
Added handling for sub-directories of a synced repo.
__Testing Instructions:__
1. Open a sub directory of an already synced repo, make sure the message "You are good to go! Your repo is synced with the parent repo." is displayed.
2. Make sure Codesync menu items show that actions will be performed on parent repo.
3. Make sure you can view playback from of the parent repo by clicking the button on Codesync menu.
=> Added handling for sub-directories of a synced repo.

.gitignore, CHANGELOG.md, build.gradle, src/main/java/org/intellij/sdk/codesync/Constants.java, src/main/java/org/intellij/sdk/codesync/clients/CodeSyncClient.java, src/main/java/org/intellij/sdk/codesync/codeSyncSetup/CodeSyncSetup.java, src/main/java/org/intellij/sdk/codesync/configuration/ConfigurationFactory.java, src/main/java/org/intellij/sdk/codesync/configuration/StagingConfiguration.java, src/main/java/org/intellij/sdk/codesync/ui/dialogs/RepoOrgSelectorDialog.java, src/main/java/org/intellij/sdk/codesync/ui/dialogs/RepoTeamSelectorDialog.java
- "Select Org" Dialogue added for Connect Repository
- "Select Team" Dialogue added for Connect Repository
- Added staging configuration to run Plugin against Staging
Org Selection
TeamSelection
=> Org/Team Selection Dialogue during Connect Repository
